### ISSUE TITLE
ios update some new emoji, like 🥶 

### ISSUE THREAD

**Issue by lanzaichen** [vdurmont/emoji-java#133]

**Comment by Pluckypan** [comment]
you can add your emoji to emojis.json

**Comment by Gab0o777** [comment]
@Pluckypan , Im having the same problem with available emojis. Since the last whatsapp update, a lot of the emojis are blank, so im looking for the best and fastest solution . is adding them to emojis.json a reliable solution? and if it is, where can i find the emoji codes to add them? the unicode character doesn't seem to be it.

Found this list , are this the codes?

https://www.unicode.org/Public/emoji/12.0/emoji-sequences.txt

**Comment by vdurmont** [comment]
I updated the JSON database with the new emojis. I will release a new version soon with those updates.
