### ISSUE TITLE
run with -Xss256k get stack overflow exception

### ISSUE THREAD

**Issue by kenvifire** [vdurmont/emoji-java#17]
I get stack overflow exception when run following test with `-Xss256k`:
<pre><code>
public class EmojiTest {
    public static void main(String[] args) {
        String str = "An 😀awesome 😃string with a few 😉emojis!";

        String resultDecimal = EmojiParser.parseToHtmlDecimal(str);
        System.out.println(resultDecimal);
    }
}
</code></pre>

and the cause is `EmojiLoader.inputStreamToString` method, which used `\A` as delimiter to read content from emojis.json. 
<pre><code>
 private static String inputStreamToString(InputStream stream) {
        Scanner s = new Scanner(stream, "UTF-8").useDelimiter("\\A");
        return s.hasNext() ? s.next() : "";
    }
</code></pre>
I don't know why you use a scanner to read the content. 
Why not just read the whole file with BuffredReader, which consumes less resource and is much more clearer?

**Comment by vdurmont** [comment]
Yep, the file is starting to get big an the scanner is not efficient for this case.
The BufferedReader is not "clearer", it's just more appropriate here. I used the scanner because I was planning to parse the database myself to avoid importing `org.json` and I forgot to switch to something else (Scanner is awesome for the tokenization).

I'll try to change this (or feel free to send a PR).
