### ISSUE TITLE
New Emojis

### ISSUE THREAD

**Issue by pbruijnes** [vdurmont/emoji-java#3]
Apple added new emoji's this month (April). Will they be added in a certain timeframe?
http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x

**Comment by vdurmont** [comment]
Hi!

For now, emoji-java uses the emoji database of [gemoji](https://github.com/github/gemoji) and it has not been updated yet.
We can either wait for gemoji to be updated or find another source for the emojis.
I will take a look at it as soon as I can but any input is welcome! (suggestions, sources or even better, pull requests)

**Comment by pbruijnes** [comment]
It would be awesome if they update their library. In the meanwhile i'll see if I can find another source!

**Comment by vdurmont** [comment]
I did a little research about this update. There are 2 things to do:
* Add the new emojis (pretty easy, we just need to update the database)
* Handle the "diversity" emojis.  
In order to do that, we need to modify the behavior of the library to detect the sequences of characters of type `emoji char`+`fitzpatrick char`.

I see 2 ways to represent the data:
* Each variation of a "basic" emoji is a new `Emoji` model (each emoji representing a person will have in fact 5 different emojis)
* We add a "state" to the `Emoji` model, to specify which variation it is.

Any thoughts?

**Comment by pengzai** [comment]
have you ever update the library?

**Comment by vdurmont** [comment]
I am working on this on the [version_2 branch](https://github.com/vdurmont/emoji-java/tree/version_2).

Today, I made a first draft of the support for:
* new emojis
* Fitzpatrick modifiers

If you have some time to take a look at the [README](https://github.com/vdurmont/emoji-java/blob/version_2/README.md) on this branch and tell me what you think of the API, it would be great.

Ping @pengzai @pbruijnes 

I didn't find a source for the new emojis so I just added:
* the 14 new families (man_man_boy, woman_woman_girl, ...)
* the 198 new flags
* the "vulcan salute" hand gesture
* the support for the diversity emojis (Fitzpatrick modifiers)

Did I miss something?

**Comment by vdurmont** [comment]
I just released the [2.0.0 version](https://github.com/vdurmont/emoji-java/tree/v2.0.0)!

It should fix this issue :wink:
